# Generated by Django 4.0.4 on 2022-06-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='txt',
            field=models.TextField(default='', max_length=100000000000000000000000000000000000000000000),
        ),
    ]
