# Generated by Django 4.0.4 on 2022-06-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='forgot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('friend_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
    ]
